### ISSUE TITLE
trying to build it on linux i end up with...

### ISSUE THREAD

**Issue by alexmyczko** [pushover/pushover.github.io#1]
mkdir -p generated/
build_tmp/assembler generated/dominos.png 58 2 200 data/sources/dominos.lst
make[1]: build_tmp/assembler: Command not found
Makefile:99: recipe for target 'generated/dominos.png' failed
make[1]: *** [generated/dominos.png] Error 127

**Comment by vog** [comment]
This is strange. The "assembler" tool should have been built by the following rule:

    build_tmp/assembler: data/sources/assembler.cpp data/sources/pngsaver.h
            mkdir -p $(dir $@)
            $(CXX) ... -o $@ $<

We need more context to see why `build_tmp/assembler` has not been built. Please run the following commands and provide the full output:

    ls -l build_tmp
    make clean
    make

Also, did Povray run on your machine successfully? (Otherwise, we could prepare a release tarball containing the generated `dominos.png` file. We are about to prepare the next release anyway.)

**Comment by alexmyczko** [comment]
I do have povray on my machine, however it doesn't make a difference. The full build log is available at
http://sid.ethz.ch/debian/pushover/

**Comment by vog** [comment]
Thanks for the log. Now the issue became clear to be. I'll provide a fix as soon as possible.

**Comment by vog** [comment]
Done.

I fixed the dependencies and also added "make install" with support for DESTDIR.

Does this work for you?

**Comment by alexmyczko** [comment]
Will try tomorrow and report back...

**Comment by alexmyczko** [comment]
A new buildlog is being generated: http://sid.ethz.ch/debian/pushover/
(can take a while on this old 32-bit linux system)

**Comment by alexmyczko** [comment]
builds! installs! runs! :)
