### ISSUE TITLE
Source distribution

### ISSUE THREAD

**Issue by alexmyczko** [pushover/pushover.github.io#2]
Hi

Would be great to have tarballs (or git checkouts) without the website (maybe split that away?), and
the data/*.ogg sounds which are 30 mb as an optional data package too? Currently I'm repackaging the
source tarball, and noting these changes in debian/README.source. 

And I'm also running echo -n > data/*.ogg (zsh) to have the software not go crazy if the oggs are missing. Maybe some --nomusic option, or at least a check to keep running even if the music is not there?

**Comment by vog** [comment]
> Would be great to have tarballs (or git checkouts) without the website (maybe split that away?),

Regarding the source tarballs: I agree that the website doesn't need to go into the release tarball. And so far, it isn't. And we don't intend to put it in there.

Regarding the Git repo: Putting the website into the same branch of the same Git repo was a conscious decision, because we consider it part of the project documentation, that should develop closely together with (and be kept in sync with) the README and source code.

> and the data/*.ogg sounds which are 30 mb as an optional data package too?

I do see the advantage of splitting the binary Debian packages that way, because it helps people with a slow internet connection.

However, what is the advantage of splitting the Git repo and/or the source tarball that way? Does this make any difference to you as a Debian maintainer? Won't you build the separate "bin" and "data" packages out of the same source package anyway?

> And I'm also running echo -n > data/*.ogg (zsh) to have the software not go crazy if the oggs are missing. Maybe some --nomusic option, or at least a check to keep running even if the music is not there?

I like that idea. But to keep this issue more focused, let's discuss that aspect in a separate issue #3.

**Comment by kilobyte** [comment]
@alexmyczko: could you please remind me why the music has been dropped?  I'm afraid I either missed that or have forgotten: is it a license issue, or merely size?

If the former, then it'd be good to describe that in the packaging (both upstream and in Debian — I don't see anything that would suggest anything but GPL2+).

If the latter, then it should be up to the user to choose.  The music is an optional part of the game, and it's a disservice to the user to remove it.  The size argument is quite frail, compared to 1⎖572⎖864⎖854 byte source tarball of flightgear-data or 1⎖496⎖947⎖656 texlive-extra.

As for end-user machines, I believe that Pinebook with 16GB disk is as low as it gets for a machine with a keyboard/joystick attached; kids in sub-Saharan Africa use some 15-years old PC with a 250GB spinning disk.  Thus, the reason might be "I don't like music" but not "I don't have the disk space".

If the license is indeed kosher, then what about shipping a package "pushover-music" that is Recommended by pushover?

**Comment by alexmyczko** [comment]
Sure, reason was to save internet bandwith / disk space.

**Comment by vog** [comment]
Just to make this point clear: There are no licensing issues with the music. The music tracks were created specifically for this Free Software pushover game. We do not use any music tracks from the original game.

And yes, everything is meant to be covered by "GPLv2 or later". Of course, one might argue that it may make sense to release our music under a Creative Commons license as well. But for now, we keep things simple by just putting everything under "GPLv2 or later".

@roever has more knowledge about the licensing stuff. However, I propose to not discuss this here, but to create separate GitHub issues for licensing questions. This issue here should be kept focused on the question about including music in the source tarball or not.

**Comment by kilobyte** [comment]
In that case, things look clear to me: once #3 is fixed, the hack of 0-sized files would be no longer needed, and, as I don't suppose @alexmyczko has an issue with a 30MB tarball per an upstream release version bump, split would then apply only to binary distribution packages — ie, outside your concern.  Would this be reasonable?

**Comment by vog** [comment]
I believe there's nothing left to do in this issue, as the only open task is to be discussed in #3. Closing this for now. If there's any topic left in this issue that I forgot to cover, please open a new issue for that.
