### ISSUE TITLE
Add build and installation instructions

### ISSUE THREAD

**Issue by msiism** [pushover/pushover.github.io#35]
It would be really nice if you could add some build and installation instructions. In particular, these should contain hints as to which build and run-time dependencies one might need to install.

I've just built and installed Pushover on Devuan 2.0.0./ASCII and had to run `make` a couple of times and install a few things inbetween before it worked out, namely:
* libboost-all-dev (I'm pretty certain it's not necessary to have the whole package here.)
* libsdl-image1.2(-dev)
* libsdl-mixer1.2(-dev)
* libsdl-ttf2.0(-dev)
* povray

By the way, the game works quite nicely. I've tried some of the old levels (and, surprisingly, remembered most of the solutions).

**Comment by kilobyte** [comment]
There are nice working packages for Beowulf/Buster; I just checked that they build fine on ASCII/Stretch (with the usual hassle of debhelper 11 backport).

If you want, we can have an official backport.  Pinging maintainer @alexmyczko for opinion.

**Comment by msiism** [comment]
An official backport for Debian would be really great.

However, some people might want to or have to build from source. So, adding a few instructions on how to accomplish that would still be quite helpful.

**Comment by vog** [comment]
It's really about time to release Pushover 0.1 and as the one major improvement over 0.0.5 is the completely revised build system (simple well-tested Makefile instead of buggy autotools nonsense), every feedback especially regarding build and installation is more than welcome.

There will be a release tarball that ships with all arch-independent generated files. This will remove the Povray dependency, so Pushover can be built entirely with Free Software as long as you don't want to change or extend the set of dominoes. (And there is no plan to do that in the foreseeable future.)

Regarding Boost, the following lines in the Makefile (just grep for "boost") tell you which parts are actually needed:

```
LIBS += -lboost_filesystem
LIBS += -lboost_system
```

Having said that, I fully agree that proper build instructions are missing and should be added before release 0.1.

**Comment by kilobyte** [comment]
Povray is a fully free piece of software, and using it allows building from actual source.

**Comment by vog** [comment]
@kilobyte Thanks for the correction! I didn't use PovRay for a very long time, and I obviously missed the news when it finally became Free Software in 2013.

Having said that, I still think there is value in providing the generated sources with the source tarball. This reduces the build time by at least one order of magnitude, which may be a reasonable trade-off regarding the slightly longer download time for some users.

Distros like Debian are free to build everything nevertheless. I'm a huge fan of building from actual source, as well as reproducible build for that matter. Any Makefile improvements into the direction are welcome!

**Comment by vog** [comment]
We finally decided to remove all automatically generated entirely from the repository as well as the source tarball. The only exception are README.md and AUTHORS, which are both generated automatically from src/doc/doc.sh, but kept in the repository to comply with common conventions. Also, full build instructions are available in README.md as well as on the new project website: https://domino-chain.gitlab.io/#install
