### ISSUE TITLE
levels license?

### ISSUE THREAD

**Issue by hydrargyrum** [pushover/pushover.github.io#6]
I don't want to sound blunt, but game engine is a reimplementation, so the license is your choice, but what about the levels (which are like the original levels)?

**Comment by alexmyczko** [comment]
Pretty good question, and answers might be different depending on geography and laws. Here's a pointer (it is not even touching software remotely): https://en.wikipedia.org/wiki/Threshold_of_originality

The following could also suffer from the levels license thing: http://bub-n-bros.sourceforge.net/ and http://www.braingames.getput.com/mog/ or even http://www.lixgame.com/

What about https://www.reactos.org/ or freedos?

It is also magically interesting how it is about fonts/typefaces to me.

http://www.blplaw.com/expert-legal-insights/articles/copyright-protect-data-file-formats

**Comment by roever** [comment]
yea, the levels are a problem, but not the only one. I personally think that the ant character is the worst problem... because we don't have an artist capable of replacing it. But: the game has been abandoned for a lot of years. And there is at least one one other pushover implementation using these levels. So until we are approached by the content owners I we keep them. I also did another game: tower toppler or nebulous. It also contains the original levels and nobody complained until now... so let's cross our fingers and hope for the best

**Comment by hydrargyrum** [comment]
Ok
